### ISSUE TITLE
Does Not work with FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by programmerneo** [bhollis/jsonview#101] opened 2015-05-26 18:00 UTC
I used this all the time with Standard Firefox, I switched to FirefoxDeveloperEdition, and this plugin does not work

**Comment by Curdal** [comment] 2015-05-27 07:22
@programmerneo I've been using Firefox Dev for a while now and this extension worked fine until a recent update.
But yes there seems to be a bug somewhere now

**Comment by bhollis** [comment] 2015-05-27 15:19
I wonder if Firefox Dev is a different product code. Could you elaborate on what "does not work" means? Does it not show up as an extension at all?

**Comment by bhollis** [comment] 2015-05-27 15:30
Or it might be that e10s is turned on in Firefox Dev... which I just merged support for!

**Comment by programmerneo** [comment] 2015-05-27 17:36
It does not "json pretty", the responses, it is now plain text, 
It Did used to work for FF Developer. Stopped working.

**Comment by wavded** [comment] 2015-05-27 20:27
I also can confirm it not working in Firefox Dev Browser when I have multi-process enabled.  Works when disabled.

**Comment by bhollis** [comment] 2015-05-28 05:43
OK. I just installed FirefoxDeveloperEdition and it works fine. It would not work with multi-process enabled because the version of JSONView that is released (0.9) does not work with multi-process.

Resolving as a duplicate of #97.

**Closed by bhollis** 2015-05-28 05:43 UTC

**Comment by Curdal** [comment] 2015-05-28 08:00
Okay it seems I had multi-process enabled. So it works fine when I disable it.
Thanks

**Comment by bhollis** [comment] 2015-06-01 00:07
The new 1.0.2 version supports multi-process.
